### ISSUE TITLE
Epic - Code Execution

### ISSUE THREAD

**Issue by matheusfrancisco** [clj-codes/contest.submission-runner#5]
This issue is to add all tasks for the code execution epic and all decisions about the code execution engine:

link for the MVP Epic Code Execution: https://miro.com/app/board/uXjVKZcqpQo=/?moveToWidget=3458764584786669846&cot=14

# Tasks
- [ ] endpoint to receive a new code submission, and the caller should receive a submission id. #6 
- [ ] Start the code execution container and get the output #7 
- [ ] persist the code execution output into the database, and return to the user #8

**Comment by matheusfrancisco** [comment]
- [ ] endpoint to receive a new code submission, and the caller should receive a submission-id
- [ ] Start the code execution container and get the output
- [ ] persist the output into the database

**Comment by matheusfrancisco** [comment]
@rafaeldelboni I created 1 issue to be the epic and all the other issues be added to this one to know what issues are from each epic

**Comment by rafaeldelboni** [comment]
Security architecture proposal
![image](https://github.com/clj-codes/contest.submission-runner/assets/1683898/1b50e850-8e74-4501-97d0-4c6486dd24fa)
